# Generated by Django 4.1.10 on 2023-07-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('user', '0002_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
